version: "3.9"

services:
  app:
    image: ghcr.io/althafvly/tracker:latest
    container_name: tracker
    environment:
      - BOT_TOKEN=xxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - CHAT_ID=123456123,12345614
      - GITHUB_REPOS=docker/compose,blakeblackshear/frigate
      - GITLAB_REPOS=AuroraOSS/gplayapi
      - GENERIC_GIT_REPOS=https://git.code.sf.net/p/opencamera/code
      # optional user mode
      - TG_USER_ENABLED=false
      - TG_API_ID=xxxxx # From https://my.telegram.org/apps
      - TG_API_HASH=xxxxxxxxxxxxxxxxxxxxxxxxxxx # From https://my.telegram.org/apps
      - TG_USER_TARGETS=-12345678 # User/group chatgpt
      - CHECK_INTERVAL=900 # Check every 15 minutes

    volumes:
      - ./data:/app/data
      - ./venv:/app/venv
    restart: unless-stopped
